accounts/urls.py
from django.urls import path
from django.contrib.auth import views as auth_view
from .views import register

urlpatterns = [
    path('login/', auth_view.LoginView.as_view(), name='login'),
    path('logout/', auth_view.LogoutView.as_view(template_name='registration/logout.html'), name='logout'),
    path('register/', register, name='register')
]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('photo.urls')),
    path('accounts/', include('accounts.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

photo/urls.py
from django.urls import path
from django.views.generic.detail import DetailView

from .views import *
from .models import Photo

app_name = "photo"

urlpatterns = [
    path('', photo_list, name='photo_list'),
    path('detail/<int:pk>/', DetailView.as_view(model=Photo, template_name='photo/detail.html'), name='photo_detail'),
    path('upload/', PhotoUploadView.as_view(), name='photo_upload'),
    path('update/<int:pk>/', PhotoUpdateView.as_view(), name='photo_update'),
    path('delete/<int:pk>/', PhotoDeleteView.as_view(), name='photo_delete'),
]

accounts/models.py
from django.db import models

# Create your models here.

photo/models.py
from django.db import models
from django.urls import reverse
from django.contrib.auth.models import User


# Create your models here.
class Photo(models.Model):
    objects = None
    author = models.ForeignKey(User, on_delete=models.CASCADE, related_name="user_photos")
    photo = models.ImageField(blank=True, null=True)
    text = models.TextField()
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ['-updated']

    def __str__(self):
        return self.text

    def get_absolute_url(self):
        return reverse('photo: photo_detail', args=[str(self.id)])

accounts/forms.py
from django.contrib.auth.models import User
from django import forms


class RegisterForm(forms.ModelForm):
    password = forms.CharField(label="Password", widget=forms.PasswordInput)
    password2 = forms.CharField(label="Repeat Password", widget=forms.PasswordInput)

    class Meta:
        model = User
        fields = ['username', 'first_name', 'last_name', 'email']

    def clean_password2(self):
        cd = self.cleaned_data
        if cd['password'] != cd['password']:
            raise forms.ValidationError('Passwords not matched!')
        return cd['password2']

accounts/views.py
from django.shortcuts import render
from .forms import RegisterForm


# Create your views here.
def register(request):
    if request.method == 'POST':
        user_form = RegisterForm(request.POST)
        if user_form.is_valid():
            new_user = user_form.save(commit=False)
            new_user.set_password(user_form.cleaned_data['password'])  # 암호화
            new_user.save()  # 데이터 베이스 저장
            return render(request, 'registration/register_done.html', {"form": user_form})
    else:
        user_form = RegisterForm()
    return render(request, 'registration/register.html', {"form": user_form})

photo/views.py
from django.shortcuts import render, redirect
from django.views.generic.edit import CreateView, UpdateView, DeleteView

from .models import Photo


# Create your views here.
def photo_list(request):
    photos = Photo.objects.all()
    return render(request, "photo/list.html", {"photos": photos})


class PhotoUploadView(CreateView):
    model = Photo
    fields = ["photo", "text"]
    template_name = "photo/upload.html"

    def form_valid(self, form):
        form.instance.author_id = self.request.user.id
        if form.is_valid():
            form.instance.save()  # 데이터 베이스에 저장
            return redirect("/")  # 메인 페이지 이동
        else:
            return self.render_to_response({"form": form})


class PhotoUpdateView(UpdateView):
    model = Photo
    fields = ["photo", "text"]
    template_name = "photo/update.html"


class PhotoDeleteView(DeleteView):
    model = Photo
    success_url = "/"
    template_name = "photo/delete.html"

photo/templates/photo/delete.html
{% extends 'base.html' %}

{% block title %} - delete {% endblock %}

{% block content %}
{% for post in photos %}
<div class="row">
    <div class="col-md-2"></div>
    <div class="col-md-8 panel panel-default">
        <div class="alert alert-info">
            Do you want to delete {{ object }}?
        </div>
        <form action="" method="post" enctype="multipart/form-data">
            {{ form.as_p }}
            {% csrf_token %}
            <input type="submit" class="btn btn-primary" value="Confirm"/>
        </form>
    </div>
    <div class="col-md-2"></div>
</div>
{% endfor %}
{% endblock %}

photo/templates/photo/detail.html
{% extends 'base.html' %}

{% block title %} {{ object.text }} {% endblock %}

{% block content %}
<div class="row">
    <div class="col-md-2"></div>
    <div class="col-md-8 panel panel-default">
        <p><img src="{{ object.photo.url }}" style="width:100%;"></p>
        <button type="button" class="btn btn-xs btn-info">
            {{ object.author.username }}
        </button>
        <p>{{ object.text|linebreaksbr }}</p>
        <a href="{% url 'photo:photo_delete' pk=object.id %}" class="btn btn-outline-danger btn-sm float-right">
            Delete
        </a>
        <a href="{% url 'photo:photo_update' pk=object.id %}" class="btn btn-outline-danger btn-sm float-right">
            Update
        </a>
    </div>
    <div class="col-md-2"></div>
</div>
{% endblock %}

photo/templates/photo/list.html
{% extends 'base.html' %}

{% block title %} - List {% endblock %}

{% block content %}
{% for post in photos %}
<div class="row">
    <div class="col-md-2"></div>
    <div class="col-md-8 panel panel-default">
        <p><img src="{{ post.photo.url }}" style="width:100%;"></p>
        <button type="button" class="btn btn-xs btn-info">
            {{ post.photo.username }}
        </button>
        <p>{{ post.text|linebreaksbr }}</p>
        <p class="text-right">
            <a href="{% url 'photo:photo_detail' pk=post.id %}" class="btn btn-xs btn-success">수정하기</a>
        </p>
    </div>
    <div class="col-md-2"></div>
</div>
{% endfor %}
{% endblock %}

photo/templates/photo/update.html
{% extends 'base.html' %}

{% block title %} - update {% endblock %}

{% block content %}
{% for post in photos %}
<div class="row">
    <div class="col-md-2"></div>
    <div class="col-md-8 panel panel-default">
        <form action="" method="post" enctype="multipart/form-data">
            {{ form.as_p }}
            {% csrf_token %}
            <input type="submit" class="btn btn-primary" value="update"/>
        </form>
    </div>
    <div class="col-md-2"></div>
</div>
{% endfor %}
{% endblock %}

photo/templates/photo/upload.html
{% extends 'base.html' %}

{% block title %} - Upload {% endblock %}

{% block content %}
<div class="row">
    <div class="col-md-2"></div>
    <div class="col-md-8 panel panel-default">
        <form action="" method="post" enctype="multipart/form-data"><!-- text/plain -->
            {{ form.as_p }}
            {% csrf_token %}
            <input type="submit" class="btn btn-primary" value="upload">
        </form>
    </div>
    <div class="col-md-2"></div>
</div>
{% endblock %}

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Dstargram{% block title %}{% endblock %}</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>


</head>
<body>
    <div class="container">
        <header class="header clearfix">
        <nav class="navbar navbar-expand-lg navbar-light bg-light">
            <a class="navbar-brand" href="/">Dstargram</a>
            <ul class="nav">
                <li class="nav-item">
                    <a class="nav-link" href="/">Home</a>
                </li>
                {% if user.is_authenticated %}
                <li class="nav-item"><a class="nav-link" href="/">Welcome, {{ user.get_username }}</a></li>
                <li class="nav-item"><a class="nav-link" href="{% url 'photo:photo_upload' %}">Upload</a></li>
                <li class="nav-item"><a class="nav-link" href="{% url 'logout' %}">Logout</a></li>
                {% else %}
                <li class="nav-item"><a class="nav-link" href="{% url 'login' %}">Login</a></li>
                <li class="nav-item"><a class="nav-link" href="{% url 'register' %}">Signup</a></li>
                {% endif %}
            </ul>
        </nav>
        </header>
        {% block content %}
        {% endblock %}
        <footer class="footer">
            <p> 2022 copyright me </p>
        </footer>
    </div>
</body>
</html>